### PR TITLE
Converted me, projects and organizations to REST

### PR DESCRIPTION
**Pull request by alijared**
## Summary of the changes / Why this is an improvement

This PR converts the GQL calls in ``croud me``, ``croud projects``, and ``croud organizations`` to REST.

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by chaudum** [comment]
Do the REST calls return *exactly* the same as the GQL calls? If not, please don't forget to update the examples in the documentation.

**Comment by alijared** [comment]
> Do the REST calls return _exactly_ the same as the GQL calls? If not, please don't forget to update the examples in the documentation.

They're the same except for the the organization output, as the REST API doesn't return notification data, but I've updated the docs

**Comment by MarkusH** [comment]
Since you're not on the Cloud team anymore, @alijared, I took the liberty to rebase the branch myself

**Comment by chaudum** [comment]
Please make separate PRs for cleanup tasks and feature implementations!

**Comment by MarkusH** [comment]
> Please make separate PRs for cleanup tasks and feature implementations!

Bloody hell, I squashed the wrong commits :( Will look into it on Monday

**Pull request merged**
