### PR TITLE
Update `make` help output

### PR DESCRIPTION
**Pull request by mechanomi**

### CODE REVIEW

**Comment by lukasbals** [comment]
retest this please

**Comment by lukasbals** [comment]
retest this please

**Comment by lukasbals** [comment]
retest this please

**Comment by mechanomi** [comment]
@m-kharbat I don't appear to be able to merge this. can you help?

**Comment by lukasbals** [comment]
> @m-kharbat I don't appear to be able to merge this. can you help?

@mechanomi It's because the tests are not triggered due to a GitHub outage. It will work after they have fixed it.

**Comment by lukasbals** [comment]
retest this please

**Comment by lukasbals** [comment]
retest this please

**Pull request closed without merging**
