### PR TITLE
Modernize documentation infrastructure

### PR DESCRIPTION
**Pull request by amotl**
Hi @matthijskrul,

this patch modernizes the documentation infrastructure.

- Upgrade to the most recent "crate-docs" version.
- Use some intersphinx links instead of absolute URIs.

With kind regards,
Andreas.

### CODE REVIEW

**Comment by amotl** [comment]
Hi,

CI currently croaks on this with [1], the complainer is `mypy`:

> `croud/server.py:30: error: syntax error in type comment`

```
$ pre-commit run --all-files
Trim Trailing Whitespace.................................................Passed
black....................................................................Passed
flake8...................................................................Passed
isort....................................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 2

croud/server.py:30: error: syntax error in type comment
```


Do you know what to do about it, @SStorm or @hramezani?

With kind regards,
Andreas.

[1] https://github.com/crate/croud/runs/2739148681#step:7:27

**Comment by hramezani** [comment]
> Hi,
> 
> CI currently croaks on this with [1], the complainer is `mypy`:
> 
> > `croud/server.py:30: error: syntax error in type comment`
> 
> ```
> $ pre-commit run --all-files
> Trim Trailing Whitespace.................................................Passed
> black....................................................................Passed
> flake8...................................................................Passed
> isort....................................................................Passed
> mypy.....................................................................Failed
> - hook id: mypy
> - exit code: 2
> 
> croud/server.py:30: error: syntax error in type comment
> ```
> 
> Do you know what to do about it, @SStorm or @hramezani?
> 
> With kind regards,
> Andreas.
> 
> [1] https://github.com/crate/croud/runs/2739148681#step:7:27

I think updating `mypy` to the latest version `0.812` will fix the problem

**Comment by amotl** [comment]
Dear Hasan,

thanks for your suggestion. Unfortunately, I am still observing the same error after upgrading `mypy`, see [1].

With kind regards,
Andreas.

[1] https://github.com/crate/croud/runs/2743670332#step:7:27

**Comment by SStorm** [comment]
@amotl it seems to work for me on Linux :thinking: 
 
```
❯ ./env/bin/pre-commit run --all-files
Trim Trailing Whitespace.................................................Passed
black....................................................................Passed
flake8...................................................................Passed
isort....................................................................Passed
mypy.....................................................................Passed
```

**Review by SStorm — APPROVED** [review]
Nice work!

**Review by norosa — CHANGES_REQUESTED** [review]
this PR should include:

https://github.com/crate/crate-docs/blob/main/.readthedocs.yml

**Review by matthijskrul — APPROVED** [review]

**Comment by amotl** [comment]
Hi there,

@SStorm: It also worked on my machine (macOS), but failed on GHA.
@hramezani: Thank you for making this patch succeed on CI.
@norosa: I believe there is https://github.com/crate/croud/blob/master/.readthedocs.yml already?

With kind regards,
Andreas.

**Pull request merged**
